version: '3.8'

services:
  web:
    image: ayoubater23/expense-tracker:25
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
