version: '3.8'

services:
  vue_app:
    image: ayoubater23/expense-tracker:31
    container_name: vue_expense_tracker
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - expense_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - expense_network

networks:
  expense_network:
    driver: bridge
